<?php
/**
 * @file
 * 
 */

/**
 * Implements hook_form_alter
 * Renames 'Promote to Home Page' node-edit column, to 'Feature' for all content types
 */
function imagex_content_featured_form_alter(&$form, &$form_state, $form_id) {
  
  if(isset($form['type']['#value'])){

    $this_formid = $form['type']['#value'] . '_node_form';

    if($form_id == $this_formid) {
       $form['options']['promote']['#title'] = 'Featured' ;
    }
  }

  $queue = nodequeue_load_queue_by_name('imagex_content_featured');
  if ($form_id == 'nodequeue_arrange_subqueue_form_' . $queue->qid) {
    $form['add']['submit']['#validate'][] = 'imagex_content_featured_form_validate';
  }
}
